### ISSUE TITLE
Cannot change the default client redis port - always get default one (6379).

### ISSUE THREAD

**Issue by sguimont** [pilwon/barbeque#5]
With version 0.2.1.  I looked at the latest release the same problem is present.

This line in the file lib/index.js (line 36) is always true for a number (as lodash doc)
  if (_.isEmpty(config.port)) { config.port = C.DEFAULT_PORT; }

Should be replace with this one and everything works like a charm.
  if (_.isUndefined(config.port)) { config.port = C.DEFAULT_PORT; }

**Comment by pilwon** [comment]
Thanks @sguimont , v0.2.4 has this bug fix included.

**Comment by sguimont** [comment]
My pleasure. Thank you, you are very fast!
